name: Lint
permissions:
  contents: read

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - uses: TrueBrain/actions-flake8@v2
        with:
          flake8_version: 6.0.0
          plugins: flake8-isort==6.1.1 flake8-quotes==3.4.0 flake8-commas==4.0.0 
