name: Lint
permissions:
  contents: read

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: ruff
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - uses: astral-sh/ruff-action@v1
        with:
          args: check . --output-format github


  mypy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - run: |
          pip install poetry
          poetry install --with=mypy -E all

      - run: |
          poetry run mypy \
            --follow-untyped-imports \
            --disallow-any-unimported \
            --disallow-untyped-defs \
            --check-untyped-defs \
            --strict-equality \
            --warn-redundant-casts \
            --warn-unused-ignores \
            mandible
