name: Lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: TrueBrain/actions-flake8@v2
        with:
          flake8_version: 6.0.0
          plugins: flake8-isort==6.0.0 flake8-quotes==3.3.2
