name: Lint
permissions:
  contents: read

on:
  pull_request:

jobs:
  flake8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: "3.10"
      - uses: TrueBrain/actions-flake8@v2
        with:
          flake8_version: 7.3.0
          plugins: flake8-isort==7.0.0 flake8-quotes==3.4.0 flake8-commas==4.0.0

  ruff-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/ruff-action@v4.0.0
        with:
          version: "~=0.16.3"
          args: format --check --diff --output-format=github

  mypy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: "3.10"

      - run: |
          pip install poetry
          poetry install --with=mypy --all-extras

      - run: |
          poetry run mypy \
            --follow-untyped-imports \
            --disallow-any-unimported \
            --disallow-untyped-defs \
            --check-untyped-defs \
            --strict-equality \
            --warn-redundant-casts \
            --warn-unused-ignores \
            mandible
